### ISSUE TITLE
Moving Forward

### ISSUE THREAD

**Issue by DanielAustinLee** [DanielAustinLee/anders-game#3]
I began this project with virtually no knowledge of games programming, reading a few tutorials about creating games in Java and a few articles about game engine design. Obviously it is pretty terrible.

I will still try to work on the code but I'm considering either starting a completely new project or just redoing this one using libGDX for Java.

**Comment by ValorCat** [comment]
If you like this project idea, you could do some large-scale refactors, which I tend to find extremely refreshing. I've never even heard of libgdx but it looks super cool, might be worth it.

**Comment by DanielAustinLee** [comment]
True, I guess I'll see where it goes
